# Generated by Django 2.1.2 on 2018-10-26 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DPrevUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_made', to='dprev_backend.DPrevUser')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('datetime_reached', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoNamePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.ImageField(upload_to='photos')),
                ('name', models.CharField(max_length=100)),
                ('game_with_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_name_pairs', to='dprev_backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoNameQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_photo_link', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('correct', models.BooleanField(default=True)),
                ('corresponding_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_questions', to='dprev_backend.PhotoNamePair')),
            ],
        ),
        migrations.CreateModel(
            name='ShuffledGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_instances', to='dprev_backend.Game')),
            ],
        ),
        migrations.AddField(
            model_name='photonamequestion',
            name='game_with_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dprev_backend.ShuffledGame'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game_instance_played',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_result', to='dprev_backend.ShuffledGame'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game_played',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_result_history', to='dprev_backend.Game'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result_history', to='dprev_backend.DPrevUser'),
        ),
    ]
